ROOT=../..

BENCH_SRC   = $(wildcard src/*.cpp)
BENCHMARK   = $(subst .cpp,, $(subst src/,,$(BENCH_SRC)))

CXX=g++
DEBUG=
CXXFLAGS=-Wall -Wextra -O3 -std=c++11 $(DEBUG)
UTILS=$(ROOT)/_utils/c99/src/bp_util.c
INCLUDE=-I$(ROOT)/_utils/c99/include
LIBS=-lm
EXTRAS+=

$(BENCHMARK): $(BENCH_SRC)
	$(CXX) $(UTILS) $< -o bin/$@ $(CXXFLAGS) $(INCLUDE) $(LIBS) $(EXTRAS)

clean:
	rm -rf *.o *~
	find bin/ -type f -name "*" -exec rm  {} \;
